// src/components/LanguageDropdown.tsx
import SvgIcon from "./SvgIcon";
import { selectLanguageList, selectLanguageValue, setLanguage } from "../slices/language";
import { useStoreDispatch, useStoreSelector } from "../hooks";
import type { Language } from "../slices/language";
import type { MouseEvent } from "react";

export default function LanguageDropdown() {
  const dispatch = useStoreDispatch();
  const languageList = useStoreSelector(selectLanguageList);
  const languageValue = useStoreSelector(selectLanguageValue);

  const handleClick = (event: MouseEvent<HTMLButtonElement>) => {
    event.currentTarget.closest(".language-dropdown")?.classList.toggle("language-dropdown--active");
  };
  const handleItemClick = (event: MouseEvent<HTMLButtonElement>) => {
    event.currentTarget.closest(".language-dropdown")?.classList.toggle("language-dropdown--active");

    const languageValue = event.currentTarget.dataset.value;

    if (languageValue) {
      dispatch(setLanguage(languageValue as Language));
    }
  };

  return (
    <div className="language-dropdown">
      <button className="language-dropdown__btn" type="button" onClick={handleClick}>
        <SvgIcon className="language-dropdown__btn-flag" name={languageList[languageValue].svgName} />
        <span className="language-dropdown__btn-text">{languageList[languageValue].text}</span>
        <SvgIcon className="language-dropdown__btn-icon" name="chevron-down" />
      </button>
      <ul className="language-dropdown__list">
        {Object.entries(languageList).map(([language, languageItem]) => (
          <li className="language-dropdown__item language-dropdown-item" key={language}>
            <button
              className="language-dropdown-item__btn"
              data-value={language}
              type="button"
              onClick={handleItemClick}
            >
              <SvgIcon className="language-dropdown-item__btn-flag" name={languageItem.svgName} />
              <span className="language-dropdown-item__btn-text">{languageItem.text}</span>
            </button>
          </li>
        ))}
      </ul>
    </div>
  );
}

// src/components/LanguageDropdown.vue
<script setup lang="ts">
// Composables
import { computed, ref, watch } from 'vue';

// Types
import type { LanguageDropdownEmits, LanguageDropdownModelValue, LanguageDropdownProps } from './types';

const emit = defineEmits<LanguageDropdownEmits>();
const props = withDefaults(defineProps<LanguageDropdownProps>(), { modelValue: undefined });

const isActive = ref(false);
const value = ref<LanguageDropdownProps['modelValue']>();

const languageDropdownClass = computed<Record<string, boolean>>(() => ({
  'language-dropdown': true,
  'language-dropdown--active': isActive.value,
}));

const languageDropdownBtnClick = () => {
  isActive.value = !isActive.value;
};
const languageDropdownListBtnClick = (event: Event) => {
  isActive.value = !isActive.value;
  value.value = ((event.target as HTMLElement).closest('.list-language-dropdown__btn') as HTMLElement).dataset.value;
};
const updateModelValue = (value: LanguageDropdownModelValue) => {
  console.log('updateModelValue', value);
  emit('update:modelValue', value);
};

watch(() => props.modelValue, (newValue, oldValue) => {
  if (newValue !== undefined && newValue in props.list) {
    value.value = newValue;
  }
  else if (oldValue !== undefined && oldValue in props.list) {
    value.value = oldValue;
  }
  else {
    const listKeys = Object.keys(props.list);

    if (listKeys.length) {
      value.value = listKeys[0];
    }
  }
}, { immediate: true });
watch(() => value.value, (newValue, oldValue) => {
  console.log('watch value', newValue, oldValue);

  if (newValue) {
    updateModelValue(newValue);
  }
  else if (oldValue) {
    updateModelValue(oldValue);
  }
});
</script>

<template>
  <div :class="languageDropdownClass">
    <button
      class="language-dropdown__btn"
      type="button"
      @click="languageDropdownBtnClick"
    >
      <Component
        :is="value ? props.list[value].icon : 'svg'"
        class="language-dropdown__btn-flag"
      />
      <span
        class="language-dropdown__btn-text"
        v-text="value ? props.list[value].text : ''"
      />
      <svg class="language-dropdown__btn-icon">
        <use xlink:href="#svg-chevron-down" />
      </svg>
    </button>
    <ul class="language-dropdown__list list-language-dropdown">
      <li
        v-for="(item, itemId) in props.list"
        :key="`language_${itemId}`"
        class="list-language-dropdown__item"
      >
        <button
          class="list-language-dropdown__btn"
          :data-value="itemId"
          type="button"
          @click="languageDropdownListBtnClick"
        >
          <Component
            :is="item.icon"
            class="list-language-dropdown__btn-flag"
          />
          <span
            class="list-language-dropdown__btn-text"
            v-text="item.text"
          />
        </button>
      </li>
    </ul>
  </div>
</template>
